import { Product, Category } from "./types";

// Bug 6 fix: counts are computed after products array is defined (see bottom of file)
export const categories: Category[] = [
  { id: "all",      name: "Tất cả",    icon: "🛍️", count: 0 },
  { id: "ao",       name: "Áo",        icon: "👕", count: 0 },
  { id: "quan",     name: "Quần",      icon: "👖", count: 0 },
  { id: "vay",      name: "Váy & Đầm", icon: "👗", count: 0 },
  { id: "phu-kien", name: "Phụ kiện",  icon: "👜", count: 0 },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Áo Thun Basic Oversize",
    slug: "ao-thun-basic-oversize",
    price: 299000,
    originalPrice: 450000,
    category: "ao",
    description:
      "Áo thun basic oversize với chất liệu cotton 100% thoáng mát, co giãn tốt. Thiết kế tối giản phù hợp với nhiều phong cách khác nhau. Phù hợp mặc hàng ngày, đi chơi hoặc đi làm.",
    image: "/images/products/ao-thun-oversize.jpg",
    rating: 4.8,
    reviewCount: 234,
    badge: "hot",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Trắng", "Đen", "Xám", "Xanh navy"],
    inStock: true,
    featured: true,
  },
  {
    id: 2,
    name: "Quần Jean Skinny Cao Cấp",
    slug: "quan-jean-skinny-cao-cap",
    price: 549000,
    originalPrice: 799000,
    category: "quan",
    description:
      "Quần jean skinny with stretch fabric cao cấp, ôm dáng vừa phải, tôn lên đường cong tự nhiên. Màu xanh indigo classic không bao giờ lỗi mốt.",
    image: "/images/products/quan-jean-skinny.jpg",
    rating: 4.6,
    reviewCount: 156,
    badge: "sale",
    sizes: ["26", "27", "28", "29", "30", "31", "32"],
    colors: ["Xanh indigo", "Xanh nhạt", "Đen"],
    inStock: true,
    featured: true,
  },
  {
    id: 3,
    name: "Đầm Maxi Hoa Nhí",
    slug: "dam-maxi-hoa-nhi",
    price: 689000,
    originalPrice: 950000,
    category: "vay",
    description:
      "Đầm maxi dáng dài với họa tiết hoa nhí nhẹ nhàng, chất liệu vải lụa tơ tằm mềm mại. Thiết kế cổ V và tay bồng lãng mạn.",
    image: "/images/products/dam-maxi-hoa-nhi.jpg",
    rating: 4.9,
    reviewCount: 89,
    badge: "new",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Hồng phấn", "Trắng", "Xanh mint"],
    inStock: true,
    featured: true,
  },
  {
    id: 4,
    name: "Áo Sơ Mi Linen Trắng",
    slug: "ao-so-mi-linen-trang",
    price: 399000,
    category: "ao",
    description:
      "Áo sơ mi linen tự nhiên, thấm hút tốt, phù hợp với khí hậu nhiệt đới. Thiết kế regular fit lịch sự, phù hợp đi làm hoặc đi dạo.",
    image: "/images/products/ao-so-mi-linen.jpg",
    rating: 4.7,
    reviewCount: 312,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Be", "Xanh nhạt"],
    inStock: true,
    featured: false,
  },
  {
    id: 5,
    name: "Túi Tote Canvas In Chữ",
    slug: "tui-tote-canvas-in-chu",
    price: 199000,
    category: "phu-kien",
    description:
      "Túi tote canvas chất lượng cao với hình in nghệ thuật. Dung tích lớn, phù hợp đi học, đi chợ hoặc dạo phố. Quai túi bằng vải bố chắc chắn.",
    image: "/images/products/tui-tote-canvas.jpg",
    rating: 4.5,
    reviewCount: 445,
    badge: "hot",
    sizes: ["One Size"],
    colors: ["Trắng", "Đen", "Kem"],
    inStock: true,
    featured: true,
  },
  {
    id: 6,
    name: "Quần Shorts Kaki Túi Hộp",
    slug: "quan-shorts-kaki-tui-hop",
    price: 329000,
    originalPrice: 429000,
    category: "quan",
    description:
      "Quần shorts kaki với thiết kế túi hộp cá tính. Chất vải kaki dày dặn, không nhàu. Phù hợp với style streetwear hoặc casual.",
    image: "/images/products/quan-shorts-kaki.jpg",
    rating: 4.4,
    reviewCount: 178,
    badge: "sale",
    sizes: ["28", "29", "30", "31", "32", "34"],
    colors: ["Kaki beige", "Xanh rêu", "Đen"],
    inStock: true,
    featured: false,
  },
  {
    id: 7,
    name: "Áo Hoodie Unisex Premium",
    slug: "ao-hoodie-unisex-premium",
    price: 649000,
    category: "ao",
    description:
      "Áo hoodie unisex chất liệu cotton fleece cao cấp, giữ ấm tốt. Thiết kế oversize hiện đại với mũ 2 lớp và túi kangaroo tiện dụng.",
    image: "/images/products/ao-hoodie-premium.jpg",
    rating: 4.8,
    reviewCount: 521,
    badge: "hot",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Đen", "Xám đậm", "Navy", "Trắng kem"],
    inStock: true,
    featured: true,
  },
  {
    id: 8,
    name: "Váy Chữ A Tweed Caro",
    slug: "vay-chu-a-tweed-caro",
    price: 589000,
    originalPrice: 790000,
    category: "vay",
    description:
      "Váy chữ A chất liệu tweed caro sang trọng, phong cách vintage đầy thu hút. Phần lưng có dây kéo tiện lợi, lót bên trong mịn mát.",
    image: "/images/products/vay-tweed-caro.jpg",
    rating: 4.7,
    reviewCount: 67,
    badge: "new",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Đen trắng", "Nâu be", "Đỏ đen"],
    inStock: true,
    featured: false,
  },
  {
    id: 9,
    name: "Mũ Bucket Hat Linen",
    slug: "mu-bucket-hat-linen",
    price: 159000,
    category: "phu-kien",
    description:
      "Mũ bucket hat chất liệu linen tự nhiên, nhẹ và thoáng khí. Vành rộng che nắng hiệu quả, phù hợp mùa hè.",
    image: "/images/products/mu-bucket-hat.jpg",
    rating: 4.3,
    reviewCount: 289,
    sizes: ["Free size"],
    colors: ["Beige", "Đen", "Xanh nhạt", "Hồng"],
    inStock: true,
    featured: false,
  },
  {
    id: 10,
    name: "Áo Crop Top Crochet",
    slug: "ao-crop-top-crochet",
    price: 279000,
    category: "ao",
    description:
      "Áo crop top đan móc crochet handmade độc đáo, kiểu dáng boho chic. Thích hợp mặc đi biển, đi chơi mùa hè kết hợp quần shorts hoặc váy.",
    image: "/images/products/ao-crop-crochet.jpg",
    rating: 4.6,
    reviewCount: 103,
    badge: "new",
    sizes: ["S", "M", "L"],
    colors: ["Trắng", "Be", "Vàng kem"],
    inStock: true,
    featured: false,
  },
  {
    id: 11,
    name: "Quần Palazzo Lụa Satin",
    slug: "quan-palazzo-lua-satin",
    price: 459000,
    originalPrice: 620000,
    category: "quan",
    description:
      "Quần palazzo ống rộng chất liệu lụa satin bóng mượt. Dáng suông dài thanh lịch, tôn dáng người mặc. Dễ phối với áo tucked in hoặc crop top.",
    image: "/images/products/quan-palazzo-satin.jpg",
    rating: 4.5,
    reviewCount: 92,
    badge: "sale",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Champagne", "Đen", "Hồng nude", "Xanh cobalt"],
    inStock: true,
    featured: false,
  },
  {
    id: 12,
    name: "Ví Da Nữ Mini Flap",
    slug: "vi-da-nu-mini-flap",
    price: 349000,
    category: "phu-kien",
    description:
      "Ví da nữ mini flap thiết kế nhỏ gọn sang trọng. Chất liệu da PU cao cấp, nhiều ngăn đựng thẻ và tiền. Khoá gài kim loại mạ vàng bền đẹp.",
    image: "/images/products/vi-da-mini-flap.jpg",
    rating: 4.4,
    reviewCount: 156,
    badge: "new",
    sizes: ["One Size"],
    colors: ["Đen", "Nâu", "Be", "Hồng"],
    inStock: true,
    featured: false,
  },
  {
    id: 13,
    name: "Đầm Bodycon Nơ Vai",
    slug: "dam-bodycon-no-vai",
    price: 449000,
    originalPrice: 590000,
    category: "vay",
    description:
      "Đầm bodycon ôm dáng với điểm nhấn nơ vai nữ tính. Chất vải crepe cao cấp không nhàu, ôm sát cơ thể tôn đường cong. Phù hợp dự tiệc, hẹn hò.",
    image: "/images/products/dam-bodycon-no-vai.jpg",
    rating: 4.6,
    reviewCount: 74,
    badge: "sale",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Đỏ rượu", "Đen", "Nude"],
    inStock: true,
    featured: false,
  },
  {
    id: 14,
    name: "Áo Blazer Menswear Style",
    slug: "ao-blazer-menswear-style",
    price: 899000,
    originalPrice: 1250000,
    category: "ao",
    description:
      "Áo blazer menswear style unisex, phong cách công sở hiện đại. Chất liệu polyester blend cao cấp, cứng cáp giữ form. Phù hợp đi làm, đi sự kiện.",
    image: "/images/products/ao-blazer-menswear.jpg",
    rating: 4.9,
    reviewCount: 198,
    badge: "hot",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Đen", "Xám", "Kem", "Navy"],
    inStock: true,
    featured: true,
  },
  {
    id: 15,
    name: "Dây Chuyền Bạc Pearl",
    slug: "day-chuyen-bac-pearl",
    price: 289000,
    category: "phu-kien",
    description:
      "Dây chuyền bạc 925 đính ngọc trai nhân tạo cao cấp. Thiết kế thanh lịch, tinh tế phù hợp mọi lứa tuổi. Chiều dài điều chỉnh được.",
    image: "/images/products/day-chuyen-pearl.jpg",
    rating: 4.7,
    reviewCount: 341,
    badge: "new",
    sizes: ["40cm", "45cm"],
    colors: ["Bạc", "Vàng gold"],
    inStock: true,
    featured: false,
  },
  {
    id: 16,
    name: "Váy Wrap Floral Midi",
    slug: "vay-wrap-floral-midi",
    price: 519000,
    category: "vay",
    description:
      "Váy wrap quấn dáng midi với họa tiết hoa rực rỡ. Kiểu buộc dây linh hoạt điều chỉnh eo, phù hợp nhiều vóc dáng. Chất vải viscose mềm mát.",
    image: "/images/products/vay-wrap-floral.jpg",
    rating: 4.8,
    reviewCount: 126,
    badge: "hot",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Hoa xanh đỏ", "Hoa vàng", "Hoa tím"],
    inStock: true,
    featured: false,
  },
  {
    id: 17,
    name: "Quần Jeans Baggy Y2K",
    slug: "quan-jeans-baggy-y2k",
    price: 599000,
    category: "quan",
    description:
      "Quần jeans baggy phong cách Y2K đang hot trở lại. Dáng rộng thụng cá tính, wash acid màu lạ mắt. Kết hợp với crop top hay áo tucked in.",
    image: "/images/products/quan-jeans-baggy-y2k.jpg",
    rating: 4.5,
    reviewCount: 87,
    badge: "new",
    sizes: ["26", "27", "28", "29", "30"],
    colors: ["Xanh wash", "Xám nhạt"],
    inStock: true,
    featured: false,
  },
  {
    id: 18,
    name: "Áo Polo Basic Nam Nữ",
    slug: "ao-polo-basic-nam-nu",
    price: 349000,
    originalPrice: 450000,
    category: "ao",
    description:
      "Áo polo basic unisex chất liệu pique cotton thoáng mát. Cổ bẻ lịch sự, 3 nút cài. Phù hợp đi học, đi làm casual hoặc đi chơi.",
    image: "/images/products/ao-polo-basic.jpg",
    rating: 4.6,
    reviewCount: 267,
    badge: "sale",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Trắng", "Xanh biển", "Đỏ đô"],
    inStock: true,
    featured: false,
  },
  {
    id: 19,
    name: "Túi Xách Straw Woven",
    slug: "tui-xach-straw-woven",
    price: 399000,
    category: "phu-kien",
    description:
      "Túi xách đan rơm phong cách boho, thủ công tỉ mỉ. Thiết kế hình chữ nhật với quai da mềm. Phù hợp đi biển, picnic hoặc dạo phố mùa hè.",
    image: "/images/products/tui-straw-woven.jpg",
    rating: 4.4,
    reviewCount: 93,
    badge: "new",
    sizes: ["One Size"],
    colors: ["Natural", "Nâu"],
    inStock: true,
    featured: false,
  },
  {
    id: 20,
    name: "Áo Khoác Denim Wash",
    slug: "ao-khoac-denim-wash",
    price: 749000,
    originalPrice: 990000,
    category: "ao",
    description:
      "Áo khoác denim wash light acid, phong cách retro vintage. Thiết kế regular fit với chi tiết túi ngực và cổ bẻ classic. Phù hợp layering nhiều outfit.",
    image: "/images/products/ao-khoac-denim.jpg",
    rating: 4.7,
    reviewCount: 184,
    badge: "sale",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh nhạt", "Xanh đậm", "Trắng"],
    inStock: true,
    featured: true,
  },
  {
    id: 21,
    name: "Quần Culottes Linen Kẻ",
    slug: "quan-culottes-linen-ke",
    price: 389000,
    category: "quan",
    description:
      "Quần culottes ống rẽ quạt chất liệu linen kẻ sọc nhẹ nhàng. Lưng thun co giãn thoải mái, dáng quần thanh lịch. Phù hợp đi làm hoặc dạo phố.",
    image: "/images/products/quan-culottes-linen.jpg",
    rating: 4.3,
    reviewCount: 58,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Trắng kẻ đen", "Be kẻ nâu"],
    inStock: true,
    featured: false,
  },
  {
    id: 22,
    name: "Kính Mắt Oval Vintage",
    slug: "kinh-mat-oval-vintage",
    price: 229000,
    category: "phu-kien",
    description:
      "Kính mắt thời trang dáng oval retro vintage. Gọng kim loại thanh mảnh nhẹ nhàng, tròng kính chống UV400. Phù hợp nhiều kiểu mặt.",
    image: "/images/products/kinh-mat-oval.jpg",
    rating: 4.5,
    reviewCount: 412,
    badge: "hot",
    sizes: ["One Size"],
    colors: ["Vàng gold/nâu", "Bạc/xám", "Đen"],
    inStock: true,
    featured: false,
  },
  {
    id: 23,
    name: "Đầm Shift Tweed Hồng",
    slug: "dam-shift-tweed-hong",
    price: 790000,
    originalPrice: 1100000,
    category: "vay",
    description:
      "Đầm shift tweed màu hồng pastel sang trọng, phong cách Chanel-inspired. Viền chỉ màu và nút cài kim loại làm điểm nhấn tinh tế. Phù hợp sự kiện cao cấp.",
    image: "/images/products/dam-tweed-hong.jpg",
    rating: 4.9,
    reviewCount: 43,
    badge: "new",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Hồng pastel", "Trắng ngà"],
    inStock: true,
    featured: false,
  },
  {
    id: 24,
    name: "Áo Len Crop Knit",
    slug: "ao-len-crop-knit",
    price: 419000,
    originalPrice: 560000,
    category: "ao",
    description:
      "Áo len crop knit dệt bện nổi độc đáo, phong cách minimalist. Bo tay và gấu áo cổ điển giữ ấm. Phù hợp thời tiết se lạnh, layer cùng sơ mi bên trong.",
    image: "/images/products/ao-len-crop-knit.jpg",
    rating: 4.7,
    reviewCount: 139,
    badge: "sale",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Kem", "Nâu caramel", "Xám", "Đen"],
    inStock: true,
    featured: false,
  },
];

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
  );
}

// Bug 6 fix: populate category counts from actual products data
categories.forEach((cat) => {
  cat.count = cat.id === "all"
    ? products.length
    : products.filter((p) => p.category === cat.id).length;
});
