import type { Product, Category } from "./types";

/* ═══════════════════════════════════════════════════════════
   TechNext – Dữ liệu từ Device.pdf (25 sản phẩm)
   📱 Điện Thoại: Apple(5) Xiaomi(4) Samsung(6) = 15
   📲 Tablet:     Apple(4) Xiaomi(4) Samsung(2) = 10
═══════════════════════════════════════════════════════════ */

export const products: Product[] = [

  /* ── ĐIỆN THOẠI – APPLE (id 1–5) ── */
  {
    id: 1, name: "iPhone 17 Pro Max", slug: "iphone-17-pro-max",
    price: 36_990_000, originalPrice: 40_990_000,
    category: "dien-thoai",
    description: "iPhone 17 Pro Max – đỉnh cao Apple với chip A19 Pro, OLED 120Hz, camera 48MP+48MP+48MP, quay 8K, khung titan, iOS 26. Có bản 1TB và 2TB.",
    image: "/images/products/iphone-17-pro-max.jpg",
    rating: 4.9, reviewCount: 4120, badge: "hot",
    variants: ["256GB", "512GB", "1TB", "2TB"],
    colors: ["Cam Vũ Trụ", "Xanh Đậm", "Bạc"],
    inStock: true, featured: true,
    specs: "A19 Pro | OLED 120Hz | 48MP×3 | iOS 26 | Titan",
  },
  {
    id: 2, name: "iPhone 17 Pro", slug: "iphone-17-pro",
    price: 34_790_000, originalPrice: 38_790_000,
    category: "dien-thoai",
    description: "iPhone 17 Pro với chip A19 Pro, màn hình OLED ProMotion 120Hz, camera 48MP ba ống kính, quay ProRes 4K@120fps, iOS 26. Nhỏ gọn hơn Pro Max.",
    image: "/images/products/iphone-17-pro.jpg",
    rating: 4.9, reviewCount: 2870, badge: "new",
    variants: ["256GB", "512GB", "1TB"],
    colors: ["Cam Vũ Trụ", "Bạc", "Xanh Đậm"],
    inStock: true, featured: true,
    specs: "A19 Pro | OLED 120Hz | 48MP×3 | iOS 26 | Camera Control",
  },
  {
    id: 3, name: "iPhone 17", slug: "iphone-17",
    price: 24_490_000, originalPrice: 27_490_000,
    category: "dien-thoai",
    description: "iPhone 17 tiêu chuẩn với chip A19, OLED, camera 48MP+48MP, selfie 18MP, iOS 26. Màu sắc: Xanh Lam Khói, Xanh Lá Xô Thơm, Tím Oải Hương, Trắng, Đen.",
    image: "/images/products/iphone-17.jpg",
    rating: 4.7, reviewCount: 1950, badge: "new",
    variants: ["256GB", "512GB"],
    colors: ["Xanh Lam Khói", "Xanh Lá Xô Thơm", "Tím Oải Hương", "Trắng", "Đen"],
    inStock: true, featured: false,
    specs: "A19 | OLED | 48MP+48MP | Selfie 18MP | iOS 26",
  },
  {
    id: 4, name: "iPhone Air", slug: "iphone-air",
    price: 22_990_000, originalPrice: 25_990_000,
    category: "dien-thoai",
    description: "iPhone Air – siêu mỏng nhẹ của Apple, chip A19 Pro, OLED, camera 48MP, selfie 18MP, iOS 26. Màu: Trắng Mây, Xanh Da Trời, Đen Không Gian, Vàng Nhạt.",
    image: "/images/products/iphone-air.jpg",
    rating: 4.8, reviewCount: 1320, badge: "new",
    variants: ["256GB", "512GB", "1TB"],
    colors: ["Trắng Mây", "Xanh Da Trời", "Đen Không Gian", "Vàng Nhạt"],
    inStock: true, featured: true,
    specs: "A19 Pro | OLED | 48MP | Selfie 18MP | Siêu mỏng nhẹ",
  },
  {
    id: 5, name: "iPhone 17e", slug: "iphone-17e",
    price: 23_690_000, originalPrice: 26_690_000,
    category: "dien-thoai",
    description: "iPhone 17e – flagship tầm trung Apple, chip A19, 6.1\" Super Retina XDR 2532×1170, camera 48MP f/1.6 + Tele 2x 12MP, selfie 12MP, pin 26h video, iOS 26.",
    image: "/images/products/iphone-17e.jpg",
    rating: 4.6, reviewCount: 2450, badge: "sale",
    variants: ["256GB", "512GB"],
    colors: ["Trắng", "Đen", "Hồng"],
    inStock: true, featured: false,
    specs: "A19 | 6.1\" Super Retina XDR | 48MP+12MP | iOS 26",
  },

  /* ── ĐIỆN THOẠI – XIAOMI (id 6–9) ── */
  {
    id: 6, name: "Xiaomi 17", slug: "xiaomi-17",
    price: 21_190_000, originalPrice: 24_190_000,
    category: "dien-thoai",
    description: "Xiaomi 17 với Snapdragon 8 Elite Gen 5 (4.6GHz), LTPO AMOLED, camera Leica 50MP×3, selfie 50MP, quay 8K, RAM 12GB, Android 16.",
    image: "/images/products/xiaomi-17.jpg",
    rating: 4.7, reviewCount: 980, badge: "new",
    variants: ["256GB", "512GB"],
    colors: ["Xanh Lá", "Đen", "Xanh Dương"],
    inStock: true, featured: false,
    specs: "Snapdragon 8 Elite Gen 5 | LTPO AMOLED | Leica 50MP×3 | 8K",
  },
  {
    id: 7, name: "Xiaomi 17 Ultra", slug: "xiaomi-17-ultra",
    price: 31_190_000, originalPrice: 35_190_000,
    category: "dien-thoai",
    description: "Xiaomi 17 Ultra – flagship đỉnh Leica, camera chính 200MP, Snapdragon 8 Elite Gen 5, LTPO AMOLED, selfie 50MP, quay 8K, RAM 16GB, Android 16.",
    image: "/images/products/xiaomi-17-ultra.jpg",
    rating: 4.9, reviewCount: 1870, badge: "hot",
    variants: ["512GB", "1TB"],
    colors: ["Đen", "Trắng", "Xanh Lá"],
    inStock: true, featured: true,
    specs: "Snapdragon 8 Elite Gen 5 | LTPO AMOLED | Leica 200MP | 8K | 16GB RAM",
  },
  {
    id: 8, name: "Xiaomi 15", slug: "xiaomi-15",
    price: 18_490_000, originalPrice: 21_490_000,
    category: "dien-thoai",
    description: "Xiaomi 15 với Snapdragon 8 Elite, AMOLED, camera Leica 50MP×3, selfie 32MP, quay 8K, RAM 12GB, HyperOS 2. Màu: Xanh Lá, Đen, Trắng.",
    image: "/images/products/xiaomi-15.jpg",
    rating: 4.7, reviewCount: 1120, badge: "sale",
    variants: ["256GB", "512GB"],
    colors: ["Xanh Lá", "Đen", "Trắng"],
    inStock: true, featured: false,
    specs: "Snapdragon 8 Elite | AMOLED | Leica 50MP×3 | 8K | HyperOS 2",
  },
  {
    id: 9, name: "Xiaomi 15 Ultra", slug: "xiaomi-15-ultra",
    price: 27_490_000, originalPrice: 31_490_000,
    category: "dien-thoai",
    description: "Xiaomi 15 Ultra – Leica 4 camera (50MP+200MP+50MP+50MP), Snapdragon 8 Elite, AMOLED, selfie 32MP, quay 8K@30fps, RAM 16GB, HyperOS 2.",
    image: "/images/products/xiaomi-15-ultra.jpg",
    rating: 4.8, reviewCount: 1540, badge: "sale",
    variants: ["16GB/512GB", "16GB/1TB"],
    colors: ["Bạc", "Đen"],
    inStock: true, featured: true,
    specs: "Snapdragon 8 Elite | AMOLED | Leica 200MP | 8K | 16GB RAM",
  },

  /* ── ĐIỆN THOẠI – SAMSUNG (id 10–15) ── */
  {
    id: 10, name: "Samsung Galaxy S26 Ultra", slug: "samsung-galaxy-s26-ultra",
    price: 30_690_000, originalPrice: 35_690_000,
    category: "dien-thoai",
    description: "Galaxy S26 Ultra – Snapdragon 8 Elite Gen 5, màn 6.9\" Dynamic AMOLED 2X QHD+ 120Hz, camera 200MP+50MP+50MP+10MP, S Pen, pin 5000mAh, Android 16.",
    image: "/images/products/samsung-galaxy-s26-ultra.jpg",
    rating: 4.9, reviewCount: 2340, badge: "new",
    variants: ["12GB/256GB", "12GB/512GB", "16GB/1TB"],
    colors: ["Tím Cobalt", "Trắng Classic", "Xanh Sky Blue", "Đen Classic", "Vàng Hồng", "Bạc Shadow"],
    inStock: true, featured: true,
    specs: "Snapdragon 8 Elite Gen 5 | 6.9\" QHD+ 120Hz | 200MP | S Pen | 5000mAh",
  },
  {
    id: 11, name: "Samsung Galaxy S26+", slug: "samsung-galaxy-s26-plus",
    price: 29_990_000, originalPrice: 33_990_000,
    category: "dien-thoai",
    description: "Galaxy S26+ với Exynos 2600, 6.3\" Dynamic AMOLED 2X Full HD+, camera 50MP+12MP+10MP, selfie 12MP, pin 4300mAh sạc 25W, Android 16.",
    image: "/images/products/samsung-galaxy-s26-plus.jpg",
    rating: 4.8, reviewCount: 1230, badge: "new",
    variants: ["256GB", "512GB"],
    colors: ["Đen", "Trắng", "Xanh Da Trời", "Tím Cobalt"],
    inStock: true, featured: false,
    specs: "Exynos 2600 | 6.3\" AMOLED | 50MP+12MP+10MP | 12GB RAM",
  },
  {
    id: 12, name: "Samsung Galaxy S26", slug: "samsung-galaxy-s26",
    price: 19_990_000, originalPrice: 23_990_000,
    category: "dien-thoai",
    description: "Galaxy S26 – 10 nhân 3.8GHz, 6.3\" Dynamic AMOLED 2X 120Hz FHD+, camera 50MP+10MP+12MP, NFC, Wi-Fi 7, Bluetooth 5.4, pin 4300mAh 30h, Android 16.",
    image: "/images/products/samsung-galaxy-s26.jpg",
    rating: 4.7, reviewCount: 870, badge: "new",
    variants: ["12GB/256GB", "12GB/512GB"],
    colors: ["Tím Cobalt", "Xanh Sky Blue", "Đen Classic", "Trắng Classic", "Bạc Shadow", "Vàng Hồng"],
    inStock: true, featured: false,
    specs: "10-core 3.8GHz | 6.3\" AMOLED 120Hz | 50MP | 12GB RAM | Wi-Fi 7",
  },
  {
    id: 13, name: "Samsung Galaxy S25 Ultra", slug: "samsung-galaxy-s25-ultra",
    price: 25_490_000, originalPrice: 30_490_000,
    category: "dien-thoai",
    description: "Galaxy S25 Ultra – Snapdragon 8 Elite For Galaxy, Dynamic AMOLED 2X, camera 200MP+50MP+50MP+10MP, S Pen, Android 15, RAM 12GB.",
    image: "/images/products/samsung-galaxy-s25-ultra.jpg",
    rating: 4.8, reviewCount: 3120, badge: "sale",
    variants: ["256GB", "512GB"],
    colors: ["Xanh Titan", "Đen Titan", "Xám Titan", "Bạc Titan", "Đen Tuyền Titan", "Xanh Ngọc Titan"],
    inStock: true, featured: true,
    specs: "Snapdragon 8 Elite | Dynamic AMOLED 2X | 200MP | S Pen | Android 15",
  },
  {
    id: 14, name: "Samsung Galaxy S25+", slug: "samsung-galaxy-s25-plus",
    price: 21_700_000, originalPrice: 25_700_000,
    category: "dien-thoai",
    description: "Galaxy S25+ với Snapdragon 8 Elite For Galaxy, Dynamic AMOLED 2X, camera 50MP+12MP+10MP, selfie 12MP, quay 8K, RAM 12GB, Android 15.",
    image: "/images/products/samsung-galaxy-s25-plus.jpg",
    rating: 4.7, reviewCount: 1650, badge: "sale",
    variants: ["256GB", "512GB"],
    colors: ["Xanh Navy", "Xanh Icy", "Bạc Shadow", "Xanh Mint", "Đen Ocean", "Đỏ Coral", "Vàng Rose"],
    inStock: true, featured: false,
    specs: "Snapdragon 8 Elite | AMOLED 2X | 50MP+12MP+10MP | 8K | 12GB RAM",
  },
  {
    id: 15, name: "Samsung Galaxy S25", slug: "samsung-galaxy-s25",
    price: 16_690_000, originalPrice: 20_690_000,
    category: "dien-thoai",
    description: "Galaxy S25 – 6.2\" Dynamic AMOLED 2X 120Hz, Snapdragon 8 Elite 4.47GHz, camera 50MP+10MP+12MP, selfie 12MP, NFC, pin 4000mAh, Android 15.",
    image: "/images/products/samsung-galaxy-s25.jpg",
    rating: 4.7, reviewCount: 2890, badge: "sale",
    variants: ["256GB", "512GB"],
    colors: ["Xanh Navy", "Xanh Icy", "Bạc Shadow", "Xanh Mint", "Đen Ocean", "Đỏ Coral", "Vàng Rose"],
    inStock: true, featured: false,
    specs: "Snapdragon 8 Elite | 6.2\" AMOLED 120Hz | 50MP | 4000mAh | 12GB RAM",
  },

  /* ── TABLET – APPLE (id 16–19) ── */
  {
    id: 16, name: "iPad Pro M5", slug: "ipad-pro-m5",
    price: 28_190_000, originalPrice: 31_190_000,
    category: "tablet",
    description: "iPad Pro M5 – chip M5 mạnh nhất Apple, Ultra Retina XDR OLED 13\" 120Hz, Wi-Fi 7, Bluetooth 6.0, USB-C 4 Thunderbolt, 5G, hỗ trợ Apple Pencil Pro & Magic Keyboard.",
    image: "/images/products/ipad-pro-m5.jpg",
    rating: 4.9, reviewCount: 1340, badge: "new",
    variants: ["Wi-Fi 256GB", "Wi-Fi 512GB", "Wi-Fi 1TB", "Wi-Fi 2TB", "5G 256GB"],
    colors: ["Bạc", "Đen Không Gian"],
    inStock: true, featured: true,
    specs: "Apple M5 | 13\" OLED 120Hz | Wi-Fi 7 | USB-C 4 | Apple Pencil Pro",
  },
  {
    id: 17, name: "iPad Air M4", slug: "ipad-air-m4",
    price: 16_689_000, originalPrice: 19_689_000,
    category: "tablet",
    description: "iPad Air M4 – chip M4 8 lõi, Liquid Retina 11\" 2360×1640, camera 12MP+12MP Center Stage, RAM 12GB, iPadOS 26, hỗ trợ Apple Pencil Pro.",
    image: "/images/products/ipad-air-m4.jpg",
    rating: 4.8, reviewCount: 2110, badge: "sale",
    variants: ["Wi-Fi 128GB", "Wi-Fi 256GB", "Wi-Fi 512GB", "Wi-Fi 1TB"],
    colors: ["Xanh Dương", "Tím", "Vàng Ánh", "Bạc"],
    inStock: true, featured: true,
    specs: "Apple M4 | 11\" Liquid Retina | 12GB RAM | Apple Pencil Pro | iPadOS 26",
  },
  {
    id: 18, name: "iPad Gen 11 (2025)", slug: "ipad-gen-11",
    price: 9_290_000, originalPrice: 11_290_000,
    category: "tablet",
    description: "iPad Gen 11 (2025) – chip A16 Bionic, Liquid Retina 11\" 2360×1640 264ppi True Tone, RAM 6GB, camera 12MP+12MP Center Stage, Wi-Fi 6, USB-C, iPadOS 26.",
    image: "/images/products/ipad-gen-11.jpg",
    rating: 4.7, reviewCount: 4320, badge: "sale",
    variants: ["Wi-Fi 128GB", "Wi-Fi 256GB", "5G 128GB", "5G 256GB", "5G 512GB"],
    colors: ["Bạc", "Xám", "Hồng", "Vàng", "Xanh Dương"],
    inStock: true, featured: false,
    specs: "A16 Bionic | 11\" Liquid Retina 264ppi | 6GB RAM | Wi-Fi 6 | USB-C",
  },
  {
    id: 19, name: "iPad mini A17 Pro", slug: "ipad-mini-a17-pro",
    price: 13_090_000, originalPrice: 15_090_000,
    category: "tablet",
    description: "iPad mini A17 Pro – chip A17 Pro 6 lõi, Liquid Retina 8.3\" 2266×1488 True Tone, camera 12MP Wide+12MP UW, Apple Pencil Pro, 5G, iPadOS 18.",
    image: "/images/products/ipad-mini-a17-pro.jpg",
    rating: 4.8, reviewCount: 1560, badge: "new",
    variants: ["Wi-Fi 128GB", "Wi-Fi 256GB", "Wi-Fi 512GB"],
    colors: ["Xanh Dương", "Trắng Vàng", "Tím", "Xám"],
    inStock: true, featured: false,
    specs: "A17 Pro | 8.3\" Liquid Retina | Apple Pencil Pro | 5G | iPadOS 18",
  },

  /* ── TABLET – XIAOMI (id 20–23) ── */
  {
    id: 20, name: "Xiaomi Pad 8 Pro", slug: "xiaomi-pad-8-pro",
    price: 15_190_000, originalPrice: 17_190_000,
    category: "tablet",
    description: "Xiaomi Pad 8 Pro – Snapdragon 8 Elite, IPS LCD 11.2\" 3200×2136 144Hz 12-bit HDR10, RAM 8GB, camera 50MP+32MP, NFC, pin 9200mAh, Android 16.",
    image: "/images/products/xiaomi-pad-8-pro.jpg",
    rating: 4.8, reviewCount: 870, badge: "new",
    variants: ["8GB/128GB"],
    colors: ["Đen", "Bạc"],
    inStock: true, featured: true,
    specs: "Snapdragon 8 Elite | 11.2\" 144Hz 12-bit | 50MP+32MP | NFC | 9200mAh",
  },
  {
    id: 21, name: "Xiaomi Pad 8", slug: "xiaomi-pad-8",
    price: 10_690_000, originalPrice: 12_690_000,
    category: "tablet",
    description: "Xiaomi Pad 8 – Snapdragon 8s Gen 4, LCD 11.2\" 144Hz HDR10 Dolby Vision, RAM 8GB, camera 13MP+8MP, NFC, pin 9200mAh, Android 16.",
    image: "/images/products/xiaomi-pad-8.jpg",
    rating: 4.7, reviewCount: 630, badge: "sale",
    variants: ["8GB/128GB"],
    colors: ["Đen", "Bạc"],
    inStock: true, featured: false,
    specs: "Snapdragon 8s Gen 4 | 11.2\" 144Hz | 13MP | NFC | 9200mAh",
  },
  {
    id: 22, name: "Xiaomi Pad 7 Pro", slug: "xiaomi-pad-7-pro",
    price: 12_990_000, originalPrice: 14_990_000,
    category: "tablet",
    description: "Xiaomi Pad 7 Pro – Snapdragon 8s Gen 3 3GHz, IPS LCD 11.2\" 144Hz, RAM 8GB, camera 50MP+32MP, Wi-Fi 7, HyperOS 2. Màu: Xanh Dương, Xám, Xanh Lá.",
    image: "/images/products/xiaomi-pad-7-pro.jpg",
    rating: 4.7, reviewCount: 980, badge: "sale",
    variants: ["256GB"],
    colors: ["Xanh Dương", "Xám", "Xanh Lá"],
    inStock: true, featured: false,
    specs: "Snapdragon 8s Gen 3 | 11.2\" IPS 144Hz | 50MP+32MP | Wi-Fi 7",
  },
  {
    id: 23, name: "Xiaomi Pad 7", slug: "xiaomi-pad-7",
    price: 8_600_000, originalPrice: 10_600_000,
    category: "tablet",
    description: "Xiaomi Pad 7 – Snapdragon 7+ Gen 3 2.8GHz, IPS LCD 11.2\" 144Hz, RAM 8GB, camera 13MP+8MP, Wi-Fi 6E, HyperOS 2. Lý tưởng học sinh sinh viên.",
    image: "/images/products/xiaomi-pad-7.jpg",
    rating: 4.6, reviewCount: 1450, badge: "sale",
    variants: ["128GB", "256GB"],
    colors: ["Đen", "Bạc", "Xanh Mint"],
    inStock: true, featured: false,
    specs: "Snapdragon 7+ Gen 3 | 11.2\" 144Hz | 13MP | Wi-Fi 6E | HyperOS 2",
  },

  /* ── TABLET – SAMSUNG (id 24–25) ── */
  {
    id: 24, name: "Samsung Galaxy Tab S11 Ultra 5G", slug: "samsung-galaxy-tab-s11-ultra-5g",
    price: 32_490_000, originalPrice: 37_490_000,
    category: "tablet",
    description: "Galaxy Tab S11 Ultra 5G – Dimensity 9400+, Dynamic AMOLED 2X 14.6\" 120Hz 1848×2960, RAM 12GB, camera 13MP+8MP+12MP, S Pen, pin 11600mAh, Android 16.",
    image: "/images/products/samsung-tab-s11-ultra-5g.jpg",
    rating: 4.9, reviewCount: 760, badge: "new",
    variants: ["256GB", "1TB"],
    colors: ["Graphite", "Bạc"],
    inStock: true, featured: true,
    specs: "Dimensity 9400+ | 14.6\" AMOLED 120Hz | S Pen | 5G | 11600mAh",
  },
  {
    id: 25, name: "Samsung Galaxy Tab S11 5G", slug: "samsung-galaxy-tab-s11-5g",
    price: 19_990_000, originalPrice: 23_990_000,
    category: "tablet",
    description: "Galaxy Tab S11 5G – Dimensity 9400+, Dynamic AMOLED 2X 11\" 120Hz WQXGA, RAM 12GB, camera 13MP+12MP, S Pen, pin 8400mAh, 5G, Android 16.",
    image: "/images/products/samsung-tab-s11-5g.jpg",
    rating: 4.8, reviewCount: 1120, badge: "new",
    variants: ["128GB", "256GB"],
    colors: ["Graphite", "Bạc", "Xanh Dương"],
    inStock: true, featured: false,
    specs: "Dimensity 9400+ | 11\" AMOLED 120Hz | S Pen | 5G | 8400mAh",
  },
];

/* ── Danh mục ───────────────────────────────────────────── */
export const categories: Category[] = [
  { id: "all",        name: "Tất Cả",        icon: "🏪", count: products.length },
  { id: "dien-thoai", name: "Điện Thoại",    icon: "📱", count: products.filter(p => p.category === "dien-thoai").length },
  { id: "tablet",     name: "Máy Tính Bảng", icon: "📲", count: products.filter(p => p.category === "tablet").length },
  { id: "tai-nghe",   name: "Tai Nghe",      icon: "🎧", count: 0 },
  { id: "phu-kien",   name: "Phụ Kiện",      icon: "⌚", count: 0 },
];

/* ── Helper functions ────────────────────────────────────── */
export const getProductById = (id: number) => products.find(p => p.id === id);
export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
export const getProductsByCategory = (category: string) =>
  category === "all" ? products : products.filter(p => p.category === category);
export const getFeaturedProducts = () => products.filter(p => p.featured);
export const searchProducts = (query: string) => {
  const q = query.toLowerCase();
  return products.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    (p.specs && p.specs.toLowerCase().includes(q))
  );
};
